### ISSUE TITLE
Microfacts demo article component

### ISSUE THREAD

**Issue by tobiastykvart** [factiverse/storybook-design-system#35]
**Is your feature request related to a problem? Please describe.**
For giving demos to potential customers we want to show them how their article might look with Microfacts. Of course each of them has their own design and it will be up to them how to display Microfacts, but we can display a simplified version as a demo.
Check [this user story](https://www.notion.so/factiverse/User-Story-Experiencing-Microfacts-through-demo-20a7656d91f3488883d1b00d7179e32a) for context.

**Describe the solution you'd like**
The component should look like a typical news article. It will display:
- headline
- image (optional)
- article text
- Microfacts highlighted within the text (relies on #34 to be completed first)
<img width="790" alt="Screenshot 2022-06-11 at 13 28 57" src="https://user-images.githubusercontent.com/44401648/173186130-23af0c35-6ec1-4e5a-84ee-94388f39ab5b.png">
Ignore the slider to display more/fewer Microfacts for now.

**Comment by withchristopher** [comment]
Merged in PR #34
