### ISSUE TITLE
Fix all for publishing component library

### ISSUE THREAD

**Issue by withchristopher** [factiverse/storybook-design-system#60]
## Bug Report

**Current behavior & Fixes**
- [x] Replace Wikipedia SVG with correct file
- [x] Remove GDPR pdf from img folder
- [x] Create local exportable script for testing before publishing to NPM.
- [x] Export all correct folder from src/* to dist folder. Rollup config.
- [x] Organize type file into single folder.
- [x] Update the README with up to date information for above.
- [x] Create minified package for publishing to NPM.
- [x] Create visualization of packages similar to below with new structure.

**Screenshots**
<img width="1347" alt="Screenshot 2022-09-07 at 14 38 24" src="https://user-images.githubusercontent.com/6439444/188880144-23b92f71-3595-4180-9fc4-2330d6960d61.png">

**Comment by withchristopher** [comment]
MDX-react dependency mismatch

![Screenshot 2022-09-08 at 09 55 20](https://user-images.githubusercontent.com/6439444/189067235-18e58e25-2658-48bb-b096-bd9c053df449.png)

**Comment by tobiastykvart** [comment]
I never know what to do with those.
mdx-embed isn't critical, could be removed.
